"""Add directories

Revision ID: 01f2a26a54d9
Revises: ce1436f92110
Create Date: 2025-07-21 11:31:17.317627

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01f2a26a54d9'
down_revision = 'ce1436f92110'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('directories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['directories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('parent_id', 'name', name='unique_directory_name_per_parent')
    )
    with op.batch_alter_table('directories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_directories_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_directories_parent_id'), ['parent_id'], unique=False)

    with op.batch_alter_table('tracks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('directory_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'directories', ['directory_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tracks', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('directory_id')

    with op.batch_alter_table('directories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_directories_parent_id'))
        batch_op.drop_index(batch_op.f('ix_directories_owner_id'))

    op.drop_table('directories')
    # ### end Alembic commands ###
