"""Add storage info

Revision ID: 1834f61216c4
Revises: f3420c83c396
Create Date: 2025-03-23 18:02:46.694939

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1834f61216c4'
down_revision = 'f3420c83c396'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tracks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('object_key', sa.String(length=128), nullable=False))
        batch_op.add_column(sa.Column('source_expiration', sa.DateTime(), nullable=True))
        batch_op.alter_column('source',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tracks', schema=None) as batch_op:
        batch_op.alter_column('source',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
        batch_op.drop_column('source_expiration')
        batch_op.drop_column('object_key')

    # ### end Alembic commands ###
