"""Increase source size

Revision ID: 77655d5ad009
Revises: 1834f61216c4
Create Date: 2025-03-23 22:00:08.976683

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77655d5ad009'
down_revision = '1834f61216c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tracks', schema=None) as batch_op:
        batch_op.alter_column('source',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=256),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tracks', schema=None) as batch_op:
        batch_op.alter_column('source',
               existing_type=sa.String(length=256),
               type_=sa.VARCHAR(length=128),
               existing_nullable=True)

    # ### end Alembic commands ###
