"""Add a unique constraint to playlist_tracks

Revision ID: b25413dd593a
Revises: 01f2a26a54d9
Create Date: 2025-07-25 23:51:15.820459

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b25413dd593a'
down_revision = '01f2a26a54d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('playlist_tracks', schema=None) as batch_op:
        batch_op.create_unique_constraint('unique_track_playlist', ['track_id', 'playlist_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('playlist_tracks', schema=None) as batch_op:
        batch_op.drop_constraint('unique_track_playlist', type_='unique')

    # ### end Alembic commands ###
