"""Add more patreon-related columns

Revision ID: ce1436f92110
Revises: 1214ee5b4051
Create Date: 2025-03-27 22:09:34.371099

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce1436f92110'
down_revision = '1214ee5b4051'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('patreon_id', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('patreon_last_payment', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('patreon_last_payment')
        batch_op.drop_column('patreon_id')

    # ### end Alembic commands ###
