"""Add email verification

Revision ID: e66ff956970e
Revises: 5605a6539df9
Create Date: 2025-03-19 20:10:48.546835

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e66ff956970e'
down_revision = '5605a6539df9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('verified', sa.Boolean(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('verification_code', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('verification_code_expiration', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('verification_code_expiration')
        batch_op.drop_column('verification_code')
        batch_op.drop_column('verified')

    # ### end Alembic commands ###
